import React from 'react';

const ThemeZipp = () => {
  return (
    <div>
      <header className="basic-page">
        <h1>Ghost City: Met Life&rsquo;s Gas House District Photos</h1>
        <h4>Samuel Zipp, Affiliation?</h4>
      </header>

      <section>
        <div className="full-image">
          <img 
            src="http://dev.picturingurbanrenewal.org/prod-assets/themes/images/contract-sales.jpg"
              alt='meaningful alt text'/>
            <p className="caption">caption text goes here. Source info goes here.</p>
        </div>

        <article className="narrative theme">
      
          <p className="intro">When the Metropolitan Life Insurance company announced in 1943 that it would knock down eighteen blocks of the Lower East Side of Manhattan known as the Gas House District to build a new, modern housing development called Stuyvesant Town, it may have seemed that the company took almost no interest in the old neighborhood. The Gas House District appears as little more than an afterthought in Met Life&rsquo;s official proclamations, a messy past to be transcended. The neighborhood, Met Life executive Frederick Ecker said, was a &ldquo;blighted, run-down, dilapidated area.&rdquo; The verdict was simple: it was a drain on the city&rsquo;s fiscal health. It belonged wholly to the past<sup>1</sup>. These public judgments focused on financial characteristics, in particular the neighborhood&rsquo;s damaged viability for investment and economic growth. But despite the fact that Met Life labeled the Gas House District &ldquo;blighted,&rdquo; an artifact of economic obsolecence, they strove by other means to <em>show</em> that it was simultaneously a &ldquo;slum,&rdquo; a source of social and not merely economic problems.</p>

          <p>In fact, Met Life took a very pointed and particular interest in the area. Even as they prepared to erase its actual buildings and streets from city maps, company officials took steps to preserve the District, or at least a reasonably accurate two-dimensional facsimile of the neighborhood. In fact, the Gas House District still exists today in one frozen, virtual form: a collection of photographs owned by Metropolitan Life. This ghostly archive, record of a lost and all-but-forgotten city, is a minute and careful visual account of every building, storefront, corner, vacant lot, sidewalk, and billboard in the eighteen blocks between First Avenue, Fourteenth Street, Twentieth Street, and Avenue C as they looked in the Spring and Summer of 1943, just after Met Life announced they would knock it all down for Stuyvesant Town.<sup>2</sup></p>
          <p>The unknown photographer or photographers who made these images strived for coverage, not art. They were charged with capturing a complete visual record of physical assets the company would soon purchase or take through eminent domain. For the most part, these images are a prosaic succession of streetscapes. Most are shot head-on from the street or opposite sidewalk; some are turned at an angle to capture as much frontage as possible in one frame. They look like both portraits and backdrops. They reveal the personality or character of buildings as if their facades were faces, while also serving as stages for lost and forgotten dramas.</p>
          <p>In one way they are the ultimate in documentary, even more the mute records of reality than most photographs given that classification. Although not without evidence of photographic skill, they feel artless and without agenda, sometimes even dashed off and hurried through. But they do have a purpose, that is clear enough. The effect of the whole archive is measured rather than hurried, one of counting, amassing, taking down physical facts in a visual ledger book, making a visual account of property. They were &ldquo;taken&rdquo; simply to legitimize Met Life&rsquo;s eminent domain &ldquo;takings.&rdquo; The photos operate like a visual analogue of ownership, a record to equal and buttress those stored in the company&rsquo;s rent rolls, record books, and actuarial tables.</p>
          <p>Like many architectural photos these pictures are largely devoid of people. When they do appear it is not as characters but as afterthoughts, blurry movement interrupting the stillness. Their lives or concerns are beside the point. The images also do not make use of the relations of buildings in space to tell a story of the changing cityscape. They do not make use of angles, light, or distance to reveal disjuncture, loss, or novelty. One by one, frame by frame, they seem to reveal only the facts of their contents. They show change only in hindsight and all together as a set, when the viewer knows that everything there is now gone. The neighborhood is caught and held in the stasis so many imagined for it, all possibility of change, save destruction, permanently arrested by the camera&rsquo;s arresting power of light transfer.</p>
          <p>At their heart the images were a form of evidence, and Met Life used them this way. Not only did they demonstrate ownership, they acted as proof of the neighborhood&rsquo;s decline. The company took individual images out of the archive to distribute to newspapers or for their own promotional materials, using them to make visual arguments establishing the incontrovertible difference between the old tenement neighborhood and the new towers Met Life would build there. The photographer or photographers also made sure to venture off the streets, into the back yards and crumbling, largely abandoned rear tenements of the neighborhood to find images of urban squalor and deprivation. They brought back pictures of trash-strewn yards, children playing in rubble and abandoned buildings, flapping laundry, and a bum sleeping it off in a doorway. These images, sprinkled here and there in the archive, did more than the innocuous streetscapes to naturalize the inevitable logic of Met Life&rsquo;s benevolent intervention.</p>
          <p>For instance, when one of these photos of a tenement back yard was given the caption &ldquo;A dirty and unsightly tangle of tenements,&rdquo; on a page titled &ldquo;Time moves on and a city grows,&rdquo; in a 1951 promotional booklet distributed to Stuyvesant Town residents, it assured its readers that their homes had a beneficient purpose. &ldquo;Possessed of few of the assets which modern housing standards require,&rdquo; the booklet reassured them, &ldquo;the neighborhood slowly settled into obsolescence.&rdquo; Embedded in the rhetoric of inevitable succession that was commonly used to make urban renewal the common sense model of urban progression, these photos almost spoke for themselves. They stood naturally for a past to be erased.</p>
          <p>The <em>Philadelphia Inquirer</em> put three of these images to work in a 1945 article designed to get their city moving on urban redevelopment. The photographs ran across the top of the page, over a photo of a Stuyvesant Town model. The first two were generic &ldquo;slum&rdquo; pictures: the slovenly rear entrance to a small factory and a rubble strewn tenement yard with the requisite forlorn laundry. They were empty, obvious images, but the last one gave them purpose. It showed a group of six kids sitting in a tenement yard. Three of them are lined up on an old cot, while the other three lean against a broken and battered fence that bisects the picture horizontally. The top half of the image, above the fence, is open to the sky, but filled around on all sides with tenement facades and an ailanthus tree.  The bottom half is all foreground before the fence, but the image is bisected again on a vertical diagonal by a shaft of sunlight slanting down over the roofs from the right. On the left a pile of boards and rubble is illuminated, while to the right the kids sit, all save one engulfed in the shadow dimming the right foreground corner. They are all seemingly oblivious to the camera, caught up in their comic book reading. As if this was not enough the photo editor cropped out most of the sky and much of the illuminated left foreground, so that the darkened right side swells to half the frame. The effect was simple: &ldquo;From Slums to Paradise,&rdquo; the headline announced.  A place where youthful fantasy is eclipsed, somnolently huddling in the shadows of &ldquo;outmoded&rdquo; and &ldquo;obsolescent&rdquo; tenements, the Gas House District should and would inevitably give way to the ordered world of Stuyvesant Town.<sup>4</sup></p>
          <p>The bulk of the images, though, are not so strident, and on their own, one by one, hardly so one-dimensional. The Metropolitan could depict the Gas House District as a fixed entity by selecting particular images from the archive and embedding them in pre-ordained scripts, but taken outside that framing they resist the homogeneity of stasis.  They do depict an actual world that once existed, but in freezing that world they also allow the viewer to see the various, diverse and particular character of the neighborhood, not only its arrested development. The pictures capture endless mute stories, little mundanities that nevertheless convey the neighborhood&rsquo;s lingering vitality.  The streets, while not deserted, have a lonely feel; there are few cars, and pushcart vendors and horse-drawn wagons are not uncommon. Ominously, the Metropolitan Life tower drifts hazily in the distance over some of the westernmost blocks. But it seems too small and far away for residents to notice or fear, just part of a distant skyline that hardly seems to have anything to do with the fate of this neighborhood. In these photos, this place seems withdrawn, out of place in the world&rsquo;s greatest metropolis.</p>
          <p>Still, the neighborhood is not dead.  The six or seven blocks in the northeastern corner, those with the highest concentration of small industrial shops, car yards and abandoned lots, have a desolate feel to them, but the businesses are largely functioning and active.  The other two-thirds of the neighborhood may not be bustling, but much of it looks almost prosperous. With the benefit of hindsight, the dense mix of business, residence, and industry&mdash;anathema to city planning&rsquo;s conventional wisdom at the time&mdash;make for a rich mixed-use and mixed-class streetscape. Many of the four and five story tenements that line the streets look kept up, as do other odd, older houses mixed in here and there. Abandoned buildings do not abound, although they are not rare, either. There are at least two theaters, a Murrays five-and-dime chain store, numerous ornate churches and two schools. Billboards advertise War Loans; American flags hang from fire escapes; many families have service stars in their windows, and the camera catches the bottom half of a banner strung across 15th Street: &ldquo;God Bless Our Boys.&rdquo; On the corner of 15th St. and 1st Avenue the photographer finds a man bent at the knee examining a sign in the window of Williams Furniture Shop.  &ldquo;Tenants, Owners, Business Men,&rdquo; reads a notice from the Peter Stuyvesant Landowners Group, &ldquo;Do you want to stay in your neighborhood?  Go to the public hearing against Metropolitan.&rdquo;  Hanging next to it is a clipping from the May 27, 1943 issue of <em>P.M.</em> magazine, headlined &ldquo;Shocked Experts Call for Brakes On Fantastic ‘Met Life&rsquo; Housing.&rdquo;<sup>5</sup></p>
          <p>Almost against their will, the photographs reveal that many Gas House District residents were not willing to accept the official verdict about their neighborhood. As reporters who surveyed the neighborhood discovered, residents looked on the place with simple affection, despite poverty and a declining population base. The neighborhood was the setting for the great events of ordinary life, and had become as precious to them as the people with whom they&rsquo;d shared their lives. &ldquo;My husband died here,&rdquo; lamented Mrs. Concetta Tornabene to a <em>Herald-Tribune</em> reporter, &ldquo;and I want to die here too.&rdquo; &ldquo;It hurts when you pass by and see it,&rdquo; another woman said of the ruins left in the wake of the early demolition, &ldquo;like a knife stabbing your heart.&rdquo;  Mary Kenney, a 59 year old matron on Welfare Island, lived across the hall from Vito Cali, an Italian widower. They each had a four-room cold-water flat with a common toilet in the hallway. The doors were always open, and Ms. Kenney considered Cali&rsquo;s three sons and one daughter her own children.  &ldquo;I only hope we can stay here ‘til our son comes back,&rdquo; she said, referring to Vito Jr., who was a mechanic with the Army Air Force in India.<sup>6</sup></p>
          <p>Met Life threatened what one group of social workers called the &ldquo;strong emotional ties to the familiar neighborhood,&rdquo; as well as informal, economic and social interconnections built over time. Residents felt &ldquo;a tenacious attachment to the neighborhood and a sense of belonging together, a feeling of solidarity which made them in fact a real community.&rdquo;<sup>7</sup> In the short run, national and citywide support for urban redevelopment cleared the way for Met Life to move forward with its plans, but this lost archive and the ghost city it captures reveals faint traces of the complex social worlds imperiled by &ldquo;slum clearance&rdquo;&mdash;and the kinds of urban life people would soon try to protect from the urban renewal bulldozers.</p>

          <h5>Notes</h5>
          <ol className="footnotes">
            <li>Ecker quoted in Savelson, &ldquo;Gas House Gang Down&hellip;&rdquo;; Frederick H. Ecker, Housing (With Particular Reference to New York City), Address to the Annual Conference of Mayors, February 16, 1948, 8.</li>
            <li>The photographs are organized by the block numbers on New York City Ward maps.  Thus the photos include blocks 946-951, 972-977, and 982-987.  Block 982 is missing, but there are multiple copies of some blocks.  See RG/11 Boxes 1-3, MLA.</li>
            <li>Metropolitan Life Insurance Company, Stuyvesant Town: This Is Your Home (New York; 1952) 4-5 in S12, 4/11, MLA.</li>
            <li>See Frederic V. Lewis, &ldquo;From Slums to Paradise: Firm to Build Homes For 8000 Families,&rdquo; Philadelphia Inquirer, March 1, 1945.  The photo is 949-39, in RG/11 Box 1, MLA. The St. Louis Globe Democrat used a Met Life image, juxtaposed with a photograph of Parkchester for similar ends in Treverton, &ldquo;Metropolitan Life Has Gotham Housing Plans.&rdquo;  The photos were captioned &ldquo;Slum Clearance Before and After.&rdquo;</li>
            <li>The photo is 946-69, RG/11, Box 1.  The article is &ldquo;Shocked Experts Call For Brakes on Fantastic &lsquo;Met Life&rsquo; Housing,&rdquo; <em>P.M.</em>, May 27, 1943.</li>
            <li>Abraham, &ldquo;City Has Its Displaced Persons As Stuyvesant Town Aftermath&rdquo;; Joseph Newman, &ldquo;Gas-House District Dismayed As Housing Plan Dooms Homes,&rdquo; <em>New York Herald Tribune</em>, April 19, 1943.</li>
            <li>Newman, &ldquo;Gas-House District Dismayed As Housing Plan Dooms Homes&rdquo;; &ldquo;East Side Tenants Resigned to Evictions,&rdquo; <em>New York World Telegram</em>, March 27, 1945; &ldquo;East River Slums To Go&mdash;He&rsquo;ll Stay,&rdquo; <em>New York Journal American</em>, December 5, 1944; Community Service Society, &rdquo;Attitudes about Moving and about Stuyvesant Town,&rdquo; June 6, 1945, in Uncatalogued ST Materials, MLA; Community Service Society, &ldquo;The Rehousing Needs of the Families on The Stuyvesant Town Site,&rdquo; 49-52.</li>
          </ol>
        </article>
      </section>
    </div>
  );

}

export default ThemeZipp;